FROM node:10
WORKDIR /usr/src/app/
COPY frontend ./
RUN yarn && GENERATE_SOURCEMAP=false yarn build production

FROM nginx:1.15
COPY --from=0 /usr/src/app/build /usr/src/app/build 
COPY nginx.conf /etc/nginx/nginx.conf